modLoader = "javafml"
loaderVersion = "[46,)"
license = "All Rights Reserved"

[[mods]]
    modId = "cozy"
    version = "${version}"
    displayName = "Cozy"
    authors = "Dev - ThatGravyBoat, Artist - Frogipher"
    description = "Cozy is a mod that aims to add various foods, furniture, and quality of life additions to liven up your Minecraft world!"

[[dependencies.cozy]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cozy]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cozy]]
    modId = "resourcefullib"
    mandatory = true
    versionRange = "[1,)"
    ordering = "NONE"
    side = "BOTH"
